### ISSUE TITLE
After upgrade to OC9.0: Fatal error, undefined method OC_User::getUsedBackends()

### ISSUE THREAD

**Issue by sorenweber** [loki36/user-otp#125]
After upgrading from the latest OC8 to OC9, enabling user-otp caused the following

`PHP Fatal error:  Call to undefined method OC_User::getUsedBackends() in /var/www/owncloud/apps/user_otp/appinfo/app.php on line 45`

Line 45 reads 
`$usedBackends = OC_User::getUsedBackends();`

I had to remove the apps folder because occ disable did not work but gave the PHP Fatal error instead. Any ideas on how to fix?

**Comment by kidscripter** [comment]
Im also getting this error on a fresh install.

**Comment by sorenweber** [comment]
I don't use this app anymore, and since it appears nothing is happening I close. I have switched to the OTP provided by https://apps.owncloud.com/content/show.php/TOTP+TwoFactor+(Google+Authenticator)?content=174726
